name: Deploy cramee-api to eks

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build Client image for eks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "v1.21.3"
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Load secrets and save to app.env
        run: aws secretsmanager get-secret-value --secret-id cramee --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cramee-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
      - name: Update kube config
        run: aws eks update-kubeconfig --name cramee-cluster --region ap-northeast-1

      - name: Deploy image to Amazon EKS
        working-directory: ./
        run: |
          kubectl apply -f k8s/aws-auth.yaml
          kubectl apply -f k8s/issuer.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/client-deployment.yaml
          kubectl apply -f k8s/api-deployment.yaml
          kubectl apply -f k8s/client-service.yaml
          kubectl apply -f k8s/api-service.yaml
